### ISSUE TITLE
css技巧

### ISSUE THREAD

**Issue by silif** [silif/daima#8]
#### css
```css
html{
    overflow: hidden;
}
```
#### js
```javascript
$(document.body).css('border-right',widthScrollbar + 'px solid transparent');
```
